### ISSUE TITLE
Could you give an example of transformation?

### ISSUE THREAD

**Issue by AtlantixJJ** [xapharius/pytorch-nyuv2#1]
There are a lot of transformation to specify in your dataset argument, and the example code given in README can't run. Could you please give an example of how to specify those transform arguments? Thank you.

**Comment by xapharius** [comment]
Hi, I updated the readme and simplified the signature. The reason there are so many transformation parameters is because that allows each data source to be customised independently. Eg. if you want to resize rgb and seg to different shapes.
