### ISSUE TITLE
Surface Normal Not Found

### ISSUE THREAD

**Issue by ArcherFMY** [xapharius/pytorch-nyuv2#11]
Hi,

Has the surface normal file been removed or moved to another place?
I came across the 404: NOT FOUND error when download it.

Would you mind providing a valid link to download it?

**Comment by xapharius** [comment]
Hi, it seems that Ladicky's university page, where the dataset used to be hosted, was taken down. Unfortunately, I don't know of any other place to get the dataset from. If such a link becomes available, then replacing that line of code should do the trick (assuming of course it's the same dataset with the same format).

If someone finds one please write it here, or submit a pull request. Thanks!

**Comment by xapharius** [comment]
surface normal downloads should be working now
