### ISSUE TITLE
Class description for segmentation labels

### ISSUE THREAD

**Issue by kaushal-py** [xapharius/pytorch-nyuv2#4]
Hey, I was not able to find documentation for human annotations of the 13 classes in segmentation. Specifically, what are the objects corresponding to the 13 classes? Any idea how these classes are colormapped?

**Comment by xapharius** [comment]
They are indeed non-trivial to find. There is a reference here: [https://arxiv.org/pdf/1511.07041.pdf](https://arxiv.org/pdf/1511.07041.pdf)

I updated the readme to include the classes: (0) background, (1) bed, (2) books, (3) ceiling, (4) chair, (5) floor, (6) furniture, (7) objects, (8) painting, (9) sofa, (10) table, (11) tv, (12) wall, (13) window
