### ISSUE TITLE
Does it deal with Random cropping transform ❓ [question]

### ISSUE THREAD

**Issue by anargu** [xapharius/pytorch-nyuv2#6]
Hi, first of all thanks for this contribution, it helped me to have a more clear understanding of this dataset.

I'm working with depth and segmentation data and for that I'm using random cropping transform. I'm instancing different transforms (but under the hood these transforms do the same thing for rgb, seg and depth data) for each data. However I'm not sure if it will crop the same or different region for each data (rgb, segmentation and depth data) each time __get_item__ is called.

Despite of that, I looked at the code again and I noticed you put a random.seed before each transform of the data. This intrigued me and I wonder if that random.seed is intended to tackle the random cropping in order to crop the same region on each time (rgb, segmentation, depth and rest).

**Comment by xapharius** [comment]
Hi, glad you find the script useful. Yes, you are correct that the purpose of setting those seeds is to ensure that any random transformation on the sub-datasets would be applied in the same way. As of the time I wrote the package it worked as intended and you can see that in the example in the Readme which uses cropping. I cannot guarantee it will be working for future releases of Pytorch as they might change what random number generator is being using for the transforms, so I suggest testing it before using it!

**Comment by anargu** [comment]
Thank you for the answer, I'll give a try and test it.
